version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - ./apps/api:/app/apps/api
    ports:
      - "8000:8000"
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: infra/web.Dockerfile
    volumes:
      - ./apps/web:/web
    ports:
      - "3000:3000"
    depends_on:
      - api
